/**
 * Reads all markdown docs from dist/docs/ and bundles them into
 * src/docs/data.ts as a TypeScript object. This makes docs available
 * in Workers and other environments without filesystem access.
 *
 * Run: pnpm build:docs-data
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, basename, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DOCS_DIR = join(__dirname, '..', 'dist', 'docs')
const OUTPUT = join(__dirname, '..', 'src', 'docs', 'data.ts')

const files = readdirSync(DOCS_DIR).filter((f) => f.endsWith('.md'))
const docs: Record<string, string> = {}

for (const file of files) {
  const name = basename(file, '.md')
  docs[name] = readFileSync(join(DOCS_DIR, file), 'utf-8')
}

const output = `// Auto-generated by scripts/build-docs-data.ts — do not edit manually.
// This file bundles all markdown docs as a JSON object for Workers compatibility.
// Run \`pnpm build:docs-data\` to regenerate.

export const DOCS_DATA: Record<string, string> = ${JSON.stringify(docs, null, 2)}
`

writeFileSync(OUTPUT, output)
console.log(`Bundled ${files.length} docs into src/docs/data.ts (${(Buffer.byteLength(output) / 1024).toFixed(1)}KB)`)
